In [ ]:
from google.colab import drive
drive.mount("/content/drive")
project_dir = "/content/drive/MyDrive/streamingllm"


Mounted at /content/drive


In [ ]:
%cd drive/MyDrive/streamingllm

/content/drive/MyDrive/streamingllm


In [ ]:
!python setup.py develop

running develop
/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.



In [ ]:
!pip install torch torchvision torchaudio
!pip install transformers==4.33.0 accelerate datasets evaluate wandb scikit-learn scipy sentencepiece

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 39.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.7/265.7 kB 28.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 521.2/521.2 kB 50.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 11.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 89.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 79.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 100.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 15.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 17.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.6/190.6 kB 25.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 254.0/254.0 kB 28.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 8.4 MB/s eta 0:00:00
  Attempting uninstall: 

In [ ]:
!pip install langchain
!pip install sentence_transformers
!pip install chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 809.1/809.1 kB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 10.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.1/189.1 kB 1.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 kB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=996bbfb10a46c49f08479ebe5c01861a6b1e5ba7614e13bb55011c4225e74575
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence_transformers
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.0/506.0 kB 7.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 51.9 MB/

In [ ]:
import torch
from tqdm import tqdm
import os
from transformers import AutoModelForCausalLM, AutoTokenizer, RagRetriever, RagSequenceForGeneration
from datasets import load_dataset
from torch.nn import CrossEntropyLoss
from streaming_llm.kv_cache import StartRecentKVCache
from streaming_llm.utils import parse_args, load

### ADDED #####
import numpy as np
from langchain.chains import ConversationalRetrievalChain
from langchain.retrievers import WikipediaRetriever
from langchain.vectorstores import Chroma
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
################

device = "cuda"

#### args ####
dataset_name = "wikitext"
task = "wikitext-2-raw-v1"
split = "test"
model_name_or_path = "lmsys/vicuna-7b-v1.5"
enable_start_recent_kv_cache = True
enable_pos_shift = True
start_size = 4
recent_size = 256
num_samples = 50
output_dir = "outputs/debug_wo_rag"
arg_num_eval_tokens = None
start_ret = 3
###############

##### helper #####
def find_first(arr, seq):
    arr_with_indices = torch.cat([arr.reshape(-1, 1),
                         torch.Tensor([i for i in range(arr.size(0))]).reshape(-1, 1)],
                                 dim=1)
    for i in range(arr.size(0)):
        if torch.equal(arr_with_indices[:, 0][arr != 1][i:i+seq.size(0)], seq):
            return (arr_with_indices[:,1][arr != 1][i].int(),
                    arr_with_indices[:,1][arr != 1][i + seq.size(0) - 1].int())
    return None
################
model_name = "all-MiniLM-L6-v2"
model_kwargs = {'device': 'cpu'}
embedding = HuggingFaceEmbeddings(model_name=model_name,
                                  model_kwargs=model_kwargs)
text_splitter = RecursiveCharacterTextSplitter(chunk_size=20, chunk_overlap=3)
#################



data = load_dataset(dataset_name, task, split=split)
model, tokenizer = load(model_name_or_path)



nlls = []
loss_fn = CrossEntropyLoss(reduction="none")
past_key_values = None

if enable_start_recent_kv_cache:
    if "llama" in model.config.model_type:
        k_seq_dim = v_seq_dim = 2
    elif "mpt" in model.config.model_type:
        v_seq_dim = 2
        k_seq_dim = 3
    elif "pythia" in model.config.model_type:
        k_seq_dim = v_seq_dim = 2
    elif "falcon" in model.config.model_type:
        v_seq_dim = 1
        k_seq_dim = 1
    else:
        raise ValueError(f"got {model.config.model_type}")
    kv_cache = StartRecentKVCache(
        start_size=start_size,
        recent_size=recent_size,
        k_seq_dim=k_seq_dim,
        v_seq_dim=v_seq_dim,
    )
else:
    kv_cache = None

if enable_pos_shift:
    if "llama" in model.config.model_type:
        from streaming_llm.pos_shift.modify_llama import enable_llama_pos_shift_attention

        enable_llama_pos_shift_attention(model)
    elif "falcon" in model.config.model_type:
        from streaming_llm.pos_shift.modify_falcon import (
            enable_falcon_pos_shift_attention,
        )

        enable_falcon_pos_shift_attention(model)
    elif "gpt_neox" in model.config.model_type:
        from streaming_llm.pos_shift.modify_gpt_neox import (
            enable_gpt_neox_pos_shift_attention,
        )

        enable_gpt_neox_pos_shift_attention(model)
    elif "mpt" in model.config.model_type:
        pass
    else:
        raise ValueError(f"got {model.config.model_type}")


os.makedirs(output_dir, exist_ok=True)
f = open(f"{output_dir}/log.txt", "w")
ppls = []
for k in range(0, 10*num_samples, num_samples):
    print(f"trial: {k}")
    num_eval_tokens = 0
    i = 0
    encs = None
    for text in data["text"][k : k + num_samples]:
        encodings = tokenizer(text, return_tensors="pt")

        #### ADDED ######
        if encs is None:
            encs = encodings.input_ids.clone().detach().cpu()
        else:
            encs = torch.cat([encs, encodings.input_ids.detach().cpu()], dim = 1)
        keeps = None
        if i > start_ret:
            tsofar = " ".join(data['text'][k:k+i])
            texts = text_splitter.split_text(tsofar)
            db = Chroma.from_texts(texts, embedding)
            retriever = db.as_retriever(search_kwargs={'k': 10})
            retrieved_docs = retriever.invoke(text)
            tokens = [tokenizer(doc.page_content, return_tensors="pt").input_ids for
                    doc in retrieved_docs]
            steds = [find_first(encs.flatten(), token.flatten()[1:])
                    for token in tokens]
            steds = [s for s in steds if s is not None]
            if steds:
                keeps = sum([ed - st + 1 for st, ed in steds]), steds
            else:
                print("No retrievel")
        ################


        print(encodings.input_ids[:, :10])

        seq_len = encodings.input_ids.size(1)
        print(f"seq_len: {seq_len}")
        pbar = tqdm(range(0, seq_len - 1))

        for idx in pbar:
            input_ids = encodings.input_ids[:, idx : idx + 1].to(device)
            with torch.no_grad():
                outputs = model(
                    input_ids,
                    past_key_values=past_key_values,
                    use_cache=True,
                )
                logits = outputs.logits.view(-1, model.config.vocab_size).to('cpu')
                past_key_values = outputs.past_key_values
                label = encodings.input_ids[:, idx + 1 : idx + 2].to(logits.device).view(-1)
                neg_log_likelihood = loss_fn(logits, label)
                if kv_cache is not None:
                    # changed kv_cache with keeps values to keep attention for retrieved indices
                    past_key_values = kv_cache(past_key_values, keeps=None)
                    torch.cuda.empty_cache()
            nlls.append(neg_log_likelihood)
            pbar.set_description(
                f"nll: {neg_log_likelihood.item():.2f}, ppl: {torch.exp(neg_log_likelihood).item():.2f}"
            )
            print(neg_log_likelihood.item(), file=f, flush=True)
            num_eval_tokens += 1
            if arg_num_eval_tokens is not None and num_eval_tokens >= arg_num_eval_tokens:
                break
        if arg_num_eval_tokens is not None and num_eval_tokens >= arg_num_eval_tokens:
            break
        i += 1
    f.close()

    ppl = torch.exp(torch.stack(nlls).mean())
    print(ppl.item())
    ppls.append(ppl)
    with open(f"{output_dir}/ppl.txt", "w") as f:
        f.write(f"{ppl.item()}\n")

Loading model from lmsys/vicuna-7b-v1.5 ...


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(


StartRecentKVCache: 4, 256
trial: 0
tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,  4755,   350,  5059,   357,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 17.24it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  4755,   350,  5059,   357,   338,   385,  4223,  2706]])
seq_len: 232


100%|██████████| 231/231 [00:10<00:00, 22.26it/s]


tensor([[    1, 29871,   512, 29871, 29906, 29900, 29900, 29953,  1919,   350]])
seq_len: 249


100%|██████████| 248/248 [00:12<00:00, 20.08it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 15825,   353,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 19.82it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 29871, 29906, 29900, 29900, 29900]])
seq_len: 21


100%|██████████| 20/20 [00:01<00:00, 19.95it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   512, 29871, 29906, 29900, 29900, 29900,   350,  5059]])
seq_len: 179


100%|██████████| 178/178 [00:08<00:00, 19.95it/s]


tensor([[    1, 29871,   940,   750,   263,  1162,  1038,   292,  6297,   297]])
seq_len: 273


100%|██████████| 272/272 [00:13<00:00, 19.97it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 29871, 29906, 29900, 29900, 29953]])
seq_len: 17


100%|██████████| 16/16 [00:00<00:00, 19.13it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   512, 29871, 29906, 29900, 29900, 29953,   350,  5059]])
seq_len: 253


100%|██████████| 252/252 [00:12<00:00, 19.82it/s]


tensor([[    1, 29871,   350,  5059,   357,  5810,  1127,   297,  1023, 12298]])
seq_len: 303


100%|██████████| 302/302 [00:15<00:00, 20.03it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  4643,  5275,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 20.68it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  4643,   353,   353,   353, 29871]])
seq_len: 11


100%|██████████| 10/10 [00:00<00:00, 20.30it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 22417,   353,   353,   353, 29871]])
seq_len: 11


100%|██████████| 10/10 [00:00<00:00, 20.49it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 15521,   353,   353,   353, 29871]])
seq_len: 11


100%|██████████| 10/10 [00:00<00:00, 19.44it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,  5334, 11871,   353, 29871,    13]])
seq_len: 8


100%|██████████| 7/7 [00:00<00:00, 19.99it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  5334, 11871,   313,   399,  1943,   785,   402,  5475]])
seq_len: 139


100%|██████████| 138/138 [00:06<00:00, 19.96it/s]


tensor([[    1, 29871,  8512, 12919,   540,   471,  2217,   732, 29899, 29992]])
seq_len: 134


100%|██████████| 133/133 [00:06<00:00, 19.80it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  4634,   353,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 20.32it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871, 18375,  3245, 10013, 22937, 29035, 19310,  1891,   278]])
seq_len: 210


100%|██████████| 209/209 [00:10<00:00, 20.01it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 11095,  2440,   353,   353,   353]])
seq_len: 12


100%|██████████| 11/11 [00:00<00:00, 20.13it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  7849,   310,   825,   338,  2998,   310,  5334, 11871]])
seq_len: 114


100%|██████████| 113/113 [00:05<00:00, 20.48it/s]


tensor([[    1, 29871,  5334, 11871,   525, 29879,  5637,  6423, 21734,  1156]])
seq_len: 66


100%|██████████| 65/65 [00:03<00:00, 19.78it/s]


tensor([[    1, 29871,   450,  1487,   310,   263,  9461, 21344,   732, 29899]])
seq_len: 69


100%|██████████| 68/68 [00:03<00:00, 19.98it/s]


tensor([[    1, 29871,   512,   278,  4688, 29871, 29955, 29941, 29900, 29879]])
seq_len: 151


100%|██████████| 150/150 [00:07<00:00, 19.92it/s]


tensor([[    1, 29871,  3600,  4783,  6423,  2820, 29871, 29955, 29946, 29900]])
seq_len: 75


100%|██████████| 74/74 [00:03<00:00, 19.54it/s]


tensor([[    1, 29871,   512,   278,  1120,  1227,   310, 29871, 29955, 29946]])
seq_len: 160


100%|██████████| 159/159 [00:07<00:00, 20.08it/s]


tensor([[    1, 29871,   512, 29871, 29955, 29946, 29953,  1919,   540,  6153]])
seq_len: 216


100%|██████████| 215/215 [00:10<00:00, 20.04it/s]


9.377735137939453
trial: 50
tensor([[    1, 29871,   512, 29871, 29955, 29945, 29945,  1919,   540,  4520]])
seq_len: 75


100%|██████████| 74/74 [00:03<00:00, 19.69it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  3362,   353,   353,   353, 29871]])
seq_len: 11


100%|██████████| 10/10 [00:00<00:00, 19.02it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,   530,   365,  1878,   273, 12936,   514,   291]])
seq_len: 230


100%|██████████| 229/229 [00:11<00:00, 19.93it/s]


tensor([[    1, 29871,  4358,  3689,   373,   825,   306,   505, 10600,  1549]])
seq_len: 34


100%|██████████| 33/33 [00:01<00:00, 19.71it/s]


tensor([[    1, 29871,   512, 29871, 29955, 29945, 29953,  1919, 18075,  1060]])
seq_len: 117


100%|██████████| 116/116 [00:05<00:00, 19.94it/s]


tensor([[    1, 29871,   940, 19824,   515,   678,   574,   525,   273,   278]])
seq_len: 205


100%|██████████| 204/204 [00:10<00:00, 20.10it/s]


tensor([[    1, 29871,   306,   626,  1048,   304,   885,  1633, 10395,   368]])
seq_len: 32


100%|██████████| 31/31 [00:01<00:00, 20.04it/s]


tensor([[    1, 29871,   940,  6153,   373,   297,   278, 11801,   310, 29871]])
seq_len: 73


100%|██████████| 72/72 [00:03<00:00, 21.07it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,   678,   996,   700,   353,   353]])
seq_len: 13


100%|██████████| 12/12 [00:00<00:00, 20.43it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   512,  5846, 29871, 29955, 29945, 29929,  1919,   540]])
seq_len: 221


100%|██████████| 220/220 [00:10<00:00, 20.29it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  9208,  2440,   353,   353,   353]])
seq_len: 12


100%|██████████| 11/11 [00:00<00:00, 20.36it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  3182, 12602,   574,  1919,   278,  5120,   310,   670]])
seq_len: 210


100%|██████████| 209/209 [00:10<00:00, 20.31it/s]


tensor([[    1, 29871,   512,  4779, 29871, 29955, 29953, 29947,  1919,   540]])
seq_len: 106


100%|██████████| 105/105 [00:05<00:00, 20.37it/s]


tensor([[    1, 29871, 14198, 19138,  4637,   670,  2834,   491,   378, 22368]])
seq_len: 54


100%|██████████| 53/53 [00:02<00:00, 19.80it/s]


tensor([[    1, 29871, 13866,   338,   385,  1342,   310,   697,   310,  5334]])
seq_len: 72


100%|██████████| 71/71 [00:03<00:00, 19.73it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 13976,   353,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 19.98it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871, 15976,   293,  1608,   310,  5334, 11871,   525, 29879]])
seq_len: 33


100%|██████████| 32/32 [00:01<00:00, 20.07it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  5298,   353,   353,   353, 29871]])
seq_len: 11


100%|██████████| 10/10 [00:00<00:00, 18.97it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  4001,   278,  9362, 22337, 29891,  1919, 28431,   505]])
seq_len: 126


100%|██████████| 125/125 [00:06<00:00, 19.86it/s]


tensor([[    1, 29871,  5334, 11871,   525, 29879,  8604,  6589,   526,  2729]])
seq_len: 82


100%|██████████| 81/81 [00:04<00:00, 19.90it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  3879,   284,  3033,  5049,   353]])
seq_len: 14


100%|██████████| 13/13 [00:00<00:00, 20.11it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   319,  1473, 15381,   568,  9358,   389,   300,   310]])
seq_len: 130


100%|██████████| 129/129 [00:06<00:00, 20.00it/s]


tensor([[    1, 29871,  8512,  5334, 11871,   525, 29879, 17091,  9282,   304]])
seq_len: 86


100%|██████████| 85/85 [00:04<00:00, 19.91it/s]


tensor([[    1, 29871,  5334, 11871,   525, 29879,   752,   465,   291,  1919]])
seq_len: 96


100%|██████████| 95/95 [00:04<00:00, 19.90it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  8364,   936, 12567,   663,   353]])
seq_len: 14


100%|██████████| 13/13 [00:00<00:00, 20.25it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  5334, 11871,   525, 29879,   664,   338, 18697,  2038]])
seq_len: 307


100%|██████████| 306/306 [00:15<00:00, 19.93it/s]


tensor([[    1, 29871,   450,  3006,   272,   310,   670,   664,  3939,   408]])
seq_len: 132


100%|██████████| 131/131 [00:06<00:00, 20.50it/s]


tensor([[    1, 29871,  8512,   540,  5456,   297,   599,   772,  7492,  7190]])
seq_len: 41


100%|██████████| 40/40 [00:01<00:00, 20.66it/s]


tensor([[    1, 29871, 13611,  1023,  4654, 29879,   310,  5334, 11871,   525]])
seq_len: 97


100%|██████████| 96/96 [00:04<00:00, 20.15it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   512, 25044,   663,   353,   353, 29871]])
seq_len: 11


100%|██████████| 10/10 [00:00<00:00, 19.98it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  7579,   304,   278, 25863, 28699, 18940,  1919,  5334]])
seq_len: 81


100%|██████████| 80/80 [00:03<00:00, 20.38it/s]


tensor([[    1, 29871,   512,   670, 25423,   322,  7389,  1494,   670,  4892]])
seq_len: 108


100%|██████████| 107/107 [00:05<00:00, 20.55it/s]


tensor([[    1, 29871,  2398,  1919,   408, 14198, 11486,  1919,   540,   376]])
seq_len: 157


100%|██████████| 156/156 [00:07<00:00, 20.12it/s]


tensor([[    1, 29871,   739,   471,   297,   278, 29871, 29896, 29896,   386]])
seq_len: 286


100%|██████████| 285/285 [00:14<00:00, 19.96it/s]


11.243000030517578
trial: 100
tensor([[    1, 29871,  5334, 11871,   525, 29879,  5972,   537, 13631,   304]])
seq_len: 151


100%|██████████| 150/150 [00:07<00:00, 19.95it/s]


tensor([[    1, 29871,   512,   278, 29871, 29906, 29900,   386,  6462,  1919]])
seq_len: 82


100%|██████████| 81/81 [00:04<00:00, 19.92it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,   512, 25044,   663,   373, 10369]])
seq_len: 16


100%|██████████| 15/15 [00:00<00:00, 19.78it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  5334, 11871,   525, 29879, 22309,   756,  1754,   263]])
seq_len: 90


100%|██████████| 89/89 [00:04<00:00, 19.95it/s]


tensor([[    1, 29871, 28609,   278, 29871, 29896, 29941,   386,  6462,  1919]])
seq_len: 403


100%|██████████| 402/402 [00:20<00:00, 20.04it/s]


tensor([[    1, 29871,  7133,   278, 11720,   525, 10096,  3152,   310,   278]])
seq_len: 338


100%|██████████| 337/337 [00:16<00:00, 19.94it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  4103, 18411,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 19.65it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   319, 12875,   310, 11949,   505,  1063,  1304,   297]])
seq_len: 251


100%|██████████| 250/250 [00:12<00:00, 19.88it/s]


tensor([[    1, 29871,  5901,  5578,  4097,   505,  7180,  1568,  7621,  7688]])
seq_len: 138


100%|██████████| 137/137 [00:06<00:00, 19.88it/s]


tensor([[    1, 29871,   512, 29871, 29906, 29900, 29896, 29945,  1919, 14317]])
seq_len: 47


100%|██████████| 46/46 [00:02<00:00, 19.66it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   476,   790,   887,   313,  3118,   360,  8684]])
seq_len: 15


100%|██████████| 14/14 [00:00<00:00, 20.25it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   376,   476,   790,   887,   376,   338,   263,  4823]])
seq_len: 174


100%|██████████| 173/173 [00:08<00:00, 20.14it/s]


tensor([[    1, 29871,   450,  5702,  3897,   278,  2318,   525, 29879, 25963]])
seq_len: 189


100%|██████████| 188/188 [00:09<00:00, 19.80it/s]


tensor([[    1, 29871,   530, 10259,  1384,   292,  4696,  4863,  1919,  8688]])
seq_len: 152


100%|██████████| 151/151 [00:07<00:00, 19.91it/s]


tensor([[    1, 29871,   450,  4823,   471,  5134,   297,   278,  6025,  3277]])
seq_len: 61


100%|██████████| 60/60 [00:02<00:00, 20.20it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 16585,   322,  6507,   353,   353, 29871]])
seq_len: 11


100%|██████████| 10/10 [00:00<00:00, 20.04it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   376,   476,   790,   887,   376,   471,  3971,   491]])
seq_len: 189


100%|██████████| 188/188 [00:09<00:00, 19.82it/s]


tensor([[    1, 29871,   376,   476,   790,   887,   376,   471, 10434,   408]])
seq_len: 190


100%|██████████| 189/189 [00:09<00:00, 20.63it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   422,  3283,   322, 25647,   353,   353]])
seq_len: 12


100%|██████████| 11/11 [00:00<00:00, 21.06it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   376,   476,   790,   887,   376,   338,   385,   318]])
seq_len: 250


100%|██████████| 249/249 [00:12<00:00, 20.59it/s]


tensor([[    1, 29871,   376,   476,   790,   887,   376,   471,  1532,  4520]])
seq_len: 264


100%|██████████| 263/263 [00:12<00:00, 20.59it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   422,  1050,  1455,  4180,   353,   353]])
seq_len: 12


100%|██████████| 11/11 [00:00<00:00, 20.32it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,  2323,  1754,   967, 12601, 22065, 14477,  9512]])
seq_len: 353


100%|██████████| 352/352 [00:17<00:00, 20.43it/s]


tensor([[    1, 29871,   450,  4823,  3897,  3118,   360,  8684,   525, 29879]])
seq_len: 301


100%|██████████| 300/300 [00:14<00:00, 20.08it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  6125,  4863,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 19.93it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450, 10259,  1384,   292,  4696,  4863,  1919, 10624]])
seq_len: 111


100%|██████████| 110/110 [00:05<00:00, 19.95it/s]


tensor([[    1, 29871,  1383,   327,   491,  3979, 29871, 29906, 29900, 29896]])
seq_len: 233


100%|██████████| 232/232 [00:11<00:00, 20.00it/s]


tensor([[    1, 29871,   450,  4696,  4863,  7171,  1089,   287, 29871, 29896]])
seq_len: 180


100%|██████████| 179/179 [00:08<00:00, 20.25it/s]


tensor([[    1, 29871,  6286, 11054,  1570,  1171,  1919,   263, 17737,  3406]])
seq_len: 170


100%|██████████| 169/169 [00:08<00:00, 20.18it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 10782, 21637,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 20.62it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  1094,   760,   310,   967, 22360,  1919,  3118,   360]])
seq_len: 320


100%|██████████| 319/319 [00:15<00:00, 20.55it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 17026, 18028,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 19.38it/s]


10.236494064331055
trial: 150
tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  7307,  2323, 29871,    13]])
seq_len: 6


100%|██████████| 5/5 [00:00<00:00, 20.22it/s]


tensor([[    1, 29871,   376,   476,   790,   887,   376,   785, 29871, 29941]])
seq_len: 16


100%|██████████| 15/15 [00:00<00:00, 20.21it/s]


tensor([[    1, 29871,   376, 11143, 28706,   376,   785, 29871, 29941,   584]])
seq_len: 15


100%|██████████| 14/14 [00:00<00:00, 20.64it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 24596,  1169,   322, 24127,   353,   353]])
seq_len: 12


100%|██████████| 11/11 [00:00<00:00, 20.53it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  8965,   383,  2235,   813,  5007,  1919,  5802,  1919]])
seq_len: 20


100%|██████████| 19/19 [00:00<00:00, 19.91it/s]


tensor([[    1, 29871, 17773,   974,   571,   383,   468,   295,  3502,   813]])
seq_len: 14


100%|██████████| 13/13 [00:00<00:00, 19.85it/s]


tensor([[    1, 29871, 15981,   497,  6912,   273,   813,  5684, 11210, 29871]])
seq_len: 11


100%|██████████| 10/10 [00:00<00:00, 19.98it/s]


tensor([[    1, 29871,  9583,   273,   476,   866,  5815,   813,  5007,  1919]])
seq_len: 14


100%|██████████| 13/13 [00:00<00:00, 19.81it/s]


tensor([[    1, 29871, 17773,   713, 27945,   262,   813,  5007, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 19.72it/s]


tensor([[    1, 29871,   838,  2109, 23375,  1358,   813,  5007,  1919,  3239]])
seq_len: 13


100%|██████████| 12/12 [00:00<00:00, 20.32it/s]


tensor([[    1, 29871,  1383,   514,  1627,   813,  5007, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 20.60it/s]


tensor([[    1, 29871,   390,  4479,   612,   562,   283, 29890,   813,  5007]])
seq_len: 20


100%|██████████| 19/19 [00:00<00:00, 20.45it/s]


tensor([[    1, 29871, 24596,  1169, 23430,   515, 11190,  2191,  8778,   525]])
seq_len: 17


100%|██████████| 16/16 [00:00<00:00, 20.20it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   678,  5708,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 19.99it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 18410,  8232,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 20.10it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 23708,  4955,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 20.97it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   306,   344,   732, 29899, 29992,   770,  8957]])
seq_len: 15


100%|██████████| 14/14 [00:00<00:00, 19.76it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,   306,   344,   732, 29899, 29992,   770,  8957]])
seq_len: 167


100%|██████████| 166/166 [00:08<00:00, 19.98it/s]


tensor([[    1, 29871, 19454,   278, 19390, 17789,   582,  1953,  1919,  1716]])
seq_len: 269


100%|██████████| 268/268 [00:13<00:00, 20.35it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 16585,   353,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 20.64it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,  2874,   310,   278,   383,   375, 30099,   732]])
seq_len: 121


100%|██████████| 120/120 [00:05<00:00, 20.61it/s]


tensor([[    1, 29871,   512,   278,  1156,   755,  1919,   278, 10369, 13378]])
seq_len: 266


100%|██████████| 265/265 [00:12<00:00, 20.41it/s]


tensor([[    1, 29871,   450,  6826,   310, 23273,   360,   949, 29876,  1774]])
seq_len: 194


100%|██████████| 193/193 [00:09<00:00, 20.71it/s]


tensor([[    1, 29871,   450,   937,  8957,   793, 14587,  4240,   363,   278]])
seq_len: 208


100%|██████████| 207/207 [00:10<00:00, 20.25it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 12037,   322,  6139,   353,   353, 29871]])
seq_len: 11


100%|██████████| 10/10 [00:00<00:00, 20.99it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,  6728,   310,   383,   375, 30099,   525, 29879]])
seq_len: 479


100%|██████████| 478/478 [00:23<00:00, 20.28it/s]


tensor([[    1, 29871,   450, 13968,   750,   263,  3309,   310, 29871, 29906]])
seq_len: 186


100%|██████████| 185/185 [00:09<00:00, 20.47it/s]


tensor([[    1, 29871,  7133,   278, 13968,   525,  5400,  2133,  2645,   278]])
seq_len: 245


100%|██████████| 244/244 [00:11<00:00, 20.47it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 18264, 25381,   353,   353,   353]])
seq_len: 12


100%|██████████| 11/11 [00:00<00:00, 20.30it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,   306,   344,   732, 29899, 29992,   770, 13968]])
seq_len: 593


100%|██████████| 592/592 [00:28<00:00, 20.57it/s]


tensor([[    1, 29871,  7133,  1009, 29871, 29896, 29929, 29941, 29900, 29879]])
seq_len: 315


100%|██████████| 314/314 [00:15<00:00, 20.47it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


9.115134239196777
trial: 200
tensor([[    1, 29871,   353,   353,   353,  8481,  1166,   353,   353,   353]])
seq_len: 12


100%|██████████| 11/11 [00:00<00:00, 20.50it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450, 17680, 29871, 29946, 29945,   732, 29899, 29992]])
seq_len: 249


100%|██████████| 248/248 [00:12<00:00, 20.49it/s]


tensor([[    1, 29871,  2648,  2787,  3362,  1944,  1919,   278, 18788,  1304]])
seq_len: 278


100%|██████████| 277/277 [00:13<00:00, 20.22it/s]


tensor([[    1, 29871,   450, 13968,   525, 16723,  5075,  1166, 24775,   310]])
seq_len: 527


100%|██████████| 526/526 [00:26<00:00, 20.05it/s]


tensor([[    1, 29871,   512, 29871, 29896, 29929, 29941, 29896,   785, 29871]])
seq_len: 264


100%|██████████| 263/263 [00:13<00:00, 20.14it/s]


tensor([[    1, 29871,  7133,   278,  7145,   732, 29899, 29992, 29871, 29896]])
seq_len: 360


100%|██████████| 359/359 [00:17<00:00, 20.10it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 14409,   428,   353,   353,   353]])
seq_len: 12


100%|██████████| 11/11 [00:00<00:00, 20.46it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,   306,   344,   732, 29899, 29992,   770, 13968]])
seq_len: 307


100%|██████████| 306/306 [00:15<00:00, 20.08it/s]


tensor([[    1, 29871,   450,   306,   344,   770,   892,   278,   871, 10369]])
seq_len: 267


100%|██████████| 266/266 [00:13<00:00, 19.77it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  6438,  2761,   322,  4771,   943]])
seq_len: 15


100%|██████████| 14/14 [00:00<00:00, 19.82it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  5806,   278,  4902,   310,   278,  7751,   525, 29879]])
seq_len: 352


100%|██████████| 351/351 [00:17<00:00, 20.18it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,   319, 12664,   353,   353,   353]])
seq_len: 12


100%|██████████| 11/11 [00:00<00:00, 20.10it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   306,   344,   471, 23359, 25890,   411,   385, 15780]])
seq_len: 188


100%|██████████| 187/187 [00:09<00:00, 19.90it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  1281,  3259,   304,  7498, 19515, 19638]])
seq_len: 15


100%|██████████| 14/14 [00:00<00:00, 20.64it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,   269, 18159,   310,   278,  4908,  7483, 13968]])
seq_len: 295


100%|██████████| 294/294 [00:14<00:00, 19.97it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  8481,  1166,  3620,   353,   353]])
seq_len: 13


100%|██████████| 12/12 [00:00<00:00, 20.32it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450, 18983,  7013, 27487,  1919,   278,  2594, 29890]])
seq_len: 286


100%|██████████| 285/285 [00:14<00:00, 19.97it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  2379,   523, 19810, 15196,  4110]])
seq_len: 15


100%|██████████| 14/14 [00:00<00:00, 20.79it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   319, 29871, 29955, 29900,   732, 29899, 29992,  1539]])
seq_len: 298


100%|██████████| 297/297 [00:14<00:00, 20.25it/s]


tensor([[    1, 29871,   450, 29871, 29946, 29900,   732, 29899, 29992,  1539]])
seq_len: 287


100%|██████████| 286/286 [00:14<00:00, 20.13it/s]


tensor([[    1, 29871,   450, 13968,   750,   385,  4799,  2318,   310, 29871]])
seq_len: 94


100%|██████████| 93/93 [00:04<00:00, 19.91it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  5901,  3620,   353,   353,   353]])
seq_len: 12


100%|██████████| 11/11 [00:00<00:00, 20.38it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  2860,   278,  6410,   310,   278,  5172,  8957,   793]])
seq_len: 209


100%|██████████| 208/208 [00:10<00:00, 19.97it/s]


tensor([[    1, 29871,   450, 28744,   310,   278, 16723,  5075,  1166,  1919]])
seq_len: 233


100%|██████████| 232/232 [00:12<00:00, 18.94it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  1383,  4512,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 18.13it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  6692,   353,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 18.59it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871, 19956, 12969,   292,  1919,   278,  9883, 13968,   892]])
seq_len: 468


100%|██████████| 467/467 [00:24<00:00, 19.17it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  2787,  3362,  1944,   353,   353]])
seq_len: 13


100%|██████████| 12/12 [00:00<00:00, 19.15it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  1932,  5546,  4689,   278, 14328,  3362,   373, 29871]])
seq_len: 135


100%|██████████| 134/134 [00:06<00:00, 19.46it/s]


8.368133544921875
trial: 250
tensor([[    1, 29871,  7133,   330,  5963,   708,  6694,   373, 29871, 29945]])
seq_len: 217


100%|██████████| 216/216 [00:11<00:00, 19.40it/s]


tensor([[    1, 29871,  2688,  4133,  3271,   373, 29871, 29896, 29946,  5306]])
seq_len: 123


100%|██████████| 122/122 [00:06<00:00, 18.50it/s]


tensor([[    1, 29871,  2860,  1614,  1259,   902,  7205,  3367,  1338,  1919]])
seq_len: 151


100%|██████████| 150/150 [00:07<00:00, 19.26it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,   353, 12788,   310, 20922,  2201]])
seq_len: 18


100%|██████████| 17/17 [00:00<00:00, 18.83it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871, 13899,  1179,   310, 15780,   322,  2669,  3097,  4828]])
seq_len: 372


100%|██████████| 371/371 [00:19<00:00, 19.13it/s]


tensor([[    1, 29871,  8512,   896,   750,  5714,  6958,  2645,   278,  4646]])
seq_len: 243


100%|██████████| 242/242 [00:12<00:00, 19.23it/s]


tensor([[    1, 29871,   306,   344,   471, 22630,   491, 29871, 29947, 29900]])
seq_len: 321


100%|██████████| 320/320 [00:16<00:00, 19.41it/s]


tensor([[    1, 29871,   512,  4688,  3979,   278,  6635,   481,   499, 29879]])
seq_len: 205


100%|██████████| 204/204 [00:10<00:00, 19.70it/s]


tensor([[    1, 29871,   450,   306, 29967, 29940,   769,  8459,   304,   671]])
seq_len: 297


100%|██████████| 296/296 [00:15<00:00, 19.58it/s]


tensor([[    1, 29871,   450, 13968,   892,  6077,   964, 16526, 22704, 10193]])
seq_len: 252


100%|██████████| 251/251 [00:13<00:00, 19.05it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353, 12488,   390,   361, 22284,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 18.63it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  6123,   402,   744,   376, 12488,   376,   390,   361]])
seq_len: 222


100%|██████████| 221/221 [00:11<00:00, 18.97it/s]


tensor([[    1, 29871,   512, 12755,  1919,   540,  5331,   278,  7997, 12444]])
seq_len: 118


100%|██████████| 117/117 [00:06<00:00, 19.37it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  5057,  3762,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 18.22it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   390,   361, 22284,   471,  6345,   297,  5879,   359]])
seq_len: 301


100%|██████████| 300/300 [00:15<00:00, 19.33it/s]


tensor([[    1, 29871,   739,   338,  3805,  8927,   393,   390,   361, 22284]])
seq_len: 135


100%|██████████| 134/134 [00:06<00:00, 19.75it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  6346,   353,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 19.75it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   512,   278,  6416,   310, 29871, 29896, 29929, 29946]])
seq_len: 323


100%|██████████| 322/322 [00:17<00:00, 18.80it/s]


tensor([[    1, 29871,   390,   361, 22284,   525, 29879, 12755,  6413,   471]])
seq_len: 299


100%|██████████| 298/298 [00:15<00:00, 18.76it/s]


tensor([[    1, 29871,   512,   278, 29871, 29896, 29929, 29946, 29947, 22401]])
seq_len: 115


100%|██████████| 114/114 [00:05<00:00, 19.43it/s]


tensor([[    1, 29871,  8512,   390,   361, 22284,  7743, 11582,  4249,  7145]])
seq_len: 215


100%|██████████| 214/214 [00:11<00:00, 19.06it/s]


tensor([[    1, 29871,   390,   361, 22284,   471,  5545,   697,   310,   278]])
seq_len: 109


100%|██████████| 108/108 [00:05<00:00, 19.11it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 20031,  6413,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 17.94it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   512, 29871, 29896, 29929, 29946, 29947,  1919,   390]])
seq_len: 157


100%|██████████| 156/156 [00:08<00:00, 19.23it/s]


tensor([[    1, 29871,   390,   361, 22284,  2982,   287,   263,  4982,   472]])
seq_len: 134


100%|██████████| 133/133 [00:07<00:00, 18.54it/s]


tensor([[    1, 29871,   512,  2610, 29871, 29896, 29929, 29945, 29896,  1919]])
seq_len: 268


100%|██████████| 267/267 [00:14<00:00, 18.59it/s]


tensor([[    1, 29871,  2860, 29871, 29941, 29900,  2440,   411,   399, 29933]])
seq_len: 145


100%|██████████| 144/144 [00:07<00:00, 18.97it/s]


tensor([[    1, 29871,   390,   361, 22284,   471,  1400, 16063,  5794, 22799]])
seq_len: 130


100%|██████████| 129/129 [00:06<00:00, 18.81it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 14662,   353,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 18.63it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   390,   361, 22284, 10600, 29871, 29941, 29955,   310]])
seq_len: 136


100%|██████████| 135/135 [00:07<00:00, 18.85it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353, 29871, 29896, 29929, 29941, 29941,  6479,  3745]])
seq_len: 17


100%|██████████| 16/16 [00:00<00:00, 18.29it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450, 29871, 29896, 29929, 29941, 29941,  6479,  3745]])
seq_len: 213


100%|██████████| 212/212 [00:11<00:00, 18.99it/s]


tensor([[    1, 29871,  3323, 27284,  1919,   372,  8062,  6419,   322,  1754]])
seq_len: 187


100%|██████████| 186/186 [00:09<00:00, 18.91it/s]


tensor([[    1, 29871,   853,   375,  1474,  1919,   278, 14280,  7124, 13813]])
seq_len: 71


100%|██████████| 70/70 [00:03<00:00, 19.15it/s]


8.420308113098145
trial: 300
tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 29573,  5996,  4955,   353,   353, 29871]])
seq_len: 11


100%|██████████| 10/10 [00:00<00:00, 18.78it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,  1677,  1144,   310,   278,   298,  1038, 26655]])
seq_len: 368


100%|██████████| 367/367 [00:19<00:00, 18.83it/s]


tensor([[    1, 29871,   450,   298,  1038, 26655, 12919,  5643,   278,  3236]])
seq_len: 299


100%|██████████| 298/298 [00:15<00:00, 18.75it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  4721,   862,   800,   322, 10879,   353]])
seq_len: 13


100%|██████████| 12/12 [00:00<00:00, 18.22it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  1551,  3839, 29871, 29906,  1919,   263, 22338,   310]])
seq_len: 193


100%|██████████| 192/192 [00:10<00:00, 18.73it/s]


tensor([[    1, 29871,   450, 13988,   298,  1038, 26655,  6153,   975,   470]])
seq_len: 385


100%|██████████| 384/384 [00:19<00:00, 19.29it/s]


tensor([[    1, 29871,  1932,   278, 14280,  6153, 23723,   487,   297, 13813]])
seq_len: 352


100%|██████████| 351/351 [00:17<00:00, 19.76it/s]


tensor([[    1, 29871,  2180,  3122,  3793, 29885, 17594,  1919,   278, 13638]])
seq_len: 319


100%|██████████| 318/318 [00:16<00:00, 18.84it/s]


tensor([[    1, 29871,   512,  6502,   322,   624, 29889, 10315,   347,  2302]])
seq_len: 378


100%|██████████| 377/377 [00:19<00:00, 19.13it/s]


tensor([[    1, 29871,   315,  1336, 18658,   471, 17322,  3412,   278,  7560]])
seq_len: 169


100%|██████████| 168/168 [00:08<00:00, 19.31it/s]


tensor([[    1, 29871,  5057,  1153,  7192,   497,  8581,  5685,  3689,  4822]])
seq_len: 275


100%|██████████| 274/274 [00:13<00:00, 19.99it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  2860,   755,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 19.06it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   512,   278, 15174,   314,   294,  1156,   278, 14280]])
seq_len: 32


100%|██████████| 31/31 [00:01<00:00, 19.90it/s]


tensor([[    1, 29871,  2860,   278, 14280,  1919,   278,  3086, 13211, 12520]])
seq_len: 145


100%|██████████| 144/144 [00:07<00:00, 20.20it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,  6440, 12788,   310,   405,  5867,   549,  8313]])
seq_len: 14


100%|██████████| 13/13 [00:00<00:00, 20.01it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,  6440, 12788,   310,   405,  5867,   549,  8313]])
seq_len: 122


100%|██████████| 121/121 [00:06<00:00, 19.98it/s]


tensor([[    1, 29871,  2860,   278,  3824, 12788,   310,   405,  5867,   549]])
seq_len: 115


100%|██████████| 114/114 [00:05<00:00, 19.94it/s]


tensor([[    1, 29871,   450,  5065, 14703,   310,   278, 28469,   304,   349]])
seq_len: 104


100%|██████████| 103/103 [00:05<00:00, 19.56it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 16585,   353,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 19.31it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,   349,   375,   273,  2431, 14772]])
seq_len: 15


100%|██████████| 14/14 [00:00<00:00, 19.58it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  3645,   278,   714,  8690,   310,   278, 22467,  3362]])
seq_len: 264


100%|██████████| 263/263 [00:13<00:00, 19.48it/s]


tensor([[    1, 29871,  1932,   278,  4644, 11354,   550, 26733,   278,   349]])
seq_len: 365


100%|██████████| 364/364 [00:18<00:00, 19.35it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  3839,  5503,   353,   353,   353]])
seq_len: 12


100%|██████████| 11/11 [00:00<00:00, 19.19it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   512, 18987,   967,   716,  1283,  6270,  1919,   278]])
seq_len: 151


100%|██████████| 150/150 [00:07<00:00, 19.70it/s]


tensor([[    1, 29871,  1551,  3111, 29871, 29906, 29900,  1919,   278,  4644]])
seq_len: 140


100%|██████████| 139/139 [00:07<00:00, 19.17it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 12788,   353,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 19.47it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  7133,   278,  4644, 11354,   550,   525,  3839, 29871]])
seq_len: 250


100%|██████████| 249/249 [00:12<00:00, 19.48it/s]


tensor([[    1, 29871,  7133,   278,  1833,  4723,   310,  3111,  1919,  3148]])
seq_len: 127


100%|██████████| 126/126 [00:06<00:00, 19.53it/s]


tensor([[    1, 29871,  1551,   278,  5833,  2625,   310,   278,   405,  5867]])
seq_len: 211


100%|██████████| 210/210 [00:10<00:00, 19.34it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 12788,   310,  4059,   554,   353]])
seq_len: 14


100%|██████████| 13/13 [00:00<00:00, 19.44it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  1551,   278, 14841,   732, 29899, 29992,  1556,  1652]])
seq_len: 228


100%|██████████| 227/227 [00:11<00:00, 19.47it/s]


8.438424110412598
trial: 350
tensor([[    1, 29871,  2193, 11005, 19068,   424, 23993,   390, 29889,   476]])
seq_len: 170


100%|██████████| 169/169 [00:08<00:00, 19.41it/s]


tensor([[    1, 29871,  2180, 29871, 29906, 29906,   584, 29871, 29941, 29900]])
seq_len: 157


100%|██████████| 156/156 [00:08<00:00, 19.33it/s]


tensor([[    1, 29871,   476,   283,   655,   525, 29879,  2373,  1467,   471]])
seq_len: 107


100%|██████████| 106/106 [00:05<00:00, 18.76it/s]


tensor([[    1, 29871,   450, 28998, 29871, 29929,   386,  7946,   525, 29879]])
seq_len: 155


100%|██████████| 154/154 [00:08<00:00, 18.97it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  4644, 22467, 24067,   353,   353]])
seq_len: 13


100%|██████████| 12/12 [00:00<00:00, 18.91it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871, 25065,  1919, 29871, 29945,  7800,   313, 29871, 29947]])
seq_len: 132


100%|██████████| 131/131 [00:06<00:00, 18.95it/s]


tensor([[    1, 29871, 26206,   278,  1095,   310,   278,  4098,  1023, 25238]])
seq_len: 148


100%|██████████| 147/147 [00:07<00:00, 18.56it/s]


tensor([[    1, 29871,   450, 29871, 29929,   386, 26571, 17982,   750, 20458]])
seq_len: 225


100%|██████████| 224/224 [00:11<00:00, 19.27it/s]


tensor([[    1, 29871,  2860,  6501,   373,  3111, 29871, 29941, 29896,  1919]])
seq_len: 179


100%|██████████| 178/178 [00:09<00:00, 19.06it/s]


tensor([[    1, 29871,  2648, 29871, 29906, 29896,   584, 29871, 29900, 29900]])
seq_len: 129


100%|██████████| 128/128 [00:06<00:00, 18.73it/s]


tensor([[    1, 29871,   450,   937,  4644, 22467, 24067,   472,   278,  2621]])
seq_len: 182


100%|██████████| 181/181 [00:09<00:00, 19.49it/s]


tensor([[    1, 29871,  3645, 29871, 29906, 29896,   584, 29871, 29941, 29900]])
seq_len: 122


100%|██████████| 121/121 [00:06<00:00, 19.32it/s]


tensor([[    1, 29871,  2180, 29871, 29900, 29906,   584, 29871, 29900, 29900]])
seq_len: 186


100%|██████████| 185/185 [00:09<00:00, 19.37it/s]


tensor([[    1, 29871,  2180, 29871, 29900, 29941,   584, 29871, 29900, 29900]])
seq_len: 321


100%|██████████| 320/320 [00:16<00:00, 19.35it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  3148, 29871, 29906, 29941,  5499]])
seq_len: 17


100%|██████████| 16/16 [00:00<00:00, 19.95it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  4644,   310,   278, 29871, 29929,   386, 26571, 17535]])
seq_len: 304


100%|██████████| 303/303 [00:15<00:00, 19.37it/s]


tensor([[    1, 29871,  7803, 25320,  6350,  1549,   278, 23058,   284, 17535]])
seq_len: 116


100%|██████████| 115/115 [00:06<00:00, 18.92it/s]


tensor([[    1, 29871,   450, 29871, 29946, 29906,  1757,   310,   278, 29871]])
seq_len: 208


100%|██████████| 207/207 [00:10<00:00, 20.47it/s]


tensor([[    1, 29871,  2180, 29871, 29906, 29896,   584, 29871, 29900, 29900]])
seq_len: 126


100%|██████████| 125/125 [00:06<00:00, 20.42it/s]


tensor([[    1, 29871,  1551,   278, 23058,   284,  2175,  3412,   278,  1667]])
seq_len: 188


100%|██████████| 187/187 [00:09<00:00, 20.08it/s]


tensor([[    1, 29871,  1932,  1734,   310,   278,   766,  1901,   393,   750]])
seq_len: 293


100%|██████████| 292/292 [00:15<00:00, 18.88it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  3148, 29871, 29906,   299,  7946]])
seq_len: 16


100%|██████████| 15/15 [00:00<00:00, 19.70it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871, 10949,   278,  7250,   310, 29871, 29896,  3839,   750]])
seq_len: 274


100%|██████████| 273/273 [00:14<00:00, 19.11it/s]


tensor([[    1, 29871,  2178,  2211,  1072,  7862,   310,   278, 28998, 29871]])
seq_len: 163


100%|██████████| 162/162 [00:08<00:00, 19.19it/s]


tensor([[    1, 29871,  2180, 27470,  3839, 29871, 29896,  1919,  4813,  7608]])
seq_len: 219


100%|██████████| 218/218 [00:11<00:00, 18.97it/s]


tensor([[    1, 29871,   365,   423,  2285,  3814,   267, 11492,   515,   278]])
seq_len: 272


100%|██████████| 271/271 [00:13<00:00, 19.45it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 18334,  1454, 29883,  4110,   353]])
seq_len: 14


100%|██████████| 13/13 [00:00<00:00, 18.74it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  2180, 29871, 29900, 29929,   584, 29871, 29900, 29900]])
seq_len: 207


100%|██████████| 206/206 [00:10<00:00, 19.27it/s]


tensor([[    1, 29871,  7133,   278,  7250,   310, 29871, 29896,  3839,  1919]])
seq_len: 187


100%|██████████| 186/186 [00:09<00:00, 19.63it/s]


tensor([[    1, 29871,   382, 18919,  8811,   750,   297, 23986,  2211,  1090]])
seq_len: 264


100%|██████████| 263/263 [00:13<00:00, 19.37it/s]


tensor([[    1, 29871,  1094,   278,  7250,  4502,  1919,  4593, 19512,  8459]])
seq_len: 121


100%|██████████| 120/120 [00:06<00:00, 19.27it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  4644, 22467,  6564,   353,   353]])
seq_len: 13


100%|██████████| 12/12 [00:00<00:00, 18.74it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,  6434,   373,   278,  4565,   471, 10329, 13574]])
seq_len: 149


100%|██████████| 148/148 [00:07<00:00, 19.24it/s]


tensor([[    1, 29871, 12699,   297,   278,  7250,  4644, 22467,   289,  1191]])
seq_len: 214


100%|██████████| 213/213 [00:10<00:00, 19.39it/s]


tensor([[    1, 29871,  7133,   278, 28679,  1919,  3138,  1919,   319,  6938]])
seq_len: 226


100%|██████████| 225/225 [00:11<00:00, 19.13it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,   450,  1095,   310,  9330, 11004]])
seq_len: 18


100%|██████████| 17/17 [00:00<00:00, 19.06it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   512,   278,  6839,   603,  1919,  9330, 11004,  2315]])
seq_len: 246


100%|██████████| 245/245 [00:13<00:00, 18.64it/s]


tensor([[    1, 29871,  7133,   278,  4646,  1102, 18344,  7841,  7155, 12084]])
seq_len: 180


100%|██████████| 179/179 [00:09<00:00, 19.20it/s]


8.879209518432617
trial: 400
tensor([[    1, 29871,   512,   278, 17724,   310,  3839, 29871, 29906,  1102]])
seq_len: 167


100%|██████████| 166/166 [00:08<00:00, 18.84it/s]


tensor([[    1, 29871,  2193,  1021, 17724,  1919,   278,  4644, 11354,   550]])
seq_len: 224


100%|██████████| 223/223 [00:11<00:00, 19.48it/s]


tensor([[    1, 29871,   450,  4654,  2462,  1919,  3839, 29871, 29941,  1919]])
seq_len: 250


100%|██████████| 249/249 [00:12<00:00, 19.50it/s]


tensor([[    1, 29871,  2180,  2462,  4366,   373,   278,  7250,   310, 29871]])
seq_len: 297


100%|██████████| 296/296 [00:15<00:00, 19.11it/s]


tensor([[    1, 29871,   341, 13415,   310,  9330, 11004,  2315,   305, 29884]])
seq_len: 143


100%|██████████| 142/142 [00:07<00:00, 19.00it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,   678,   574, 29891,   549,   353]])
seq_len: 14


100%|██████████| 13/13 [00:00<00:00, 18.99it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  4644,   310,   278,  3148, 29871, 29929,   386, 26571]])
seq_len: 185


100%|██████████| 184/184 [00:09<00:00, 19.37it/s]


tensor([[    1, 29871,   450,  4644, 11354,   550, 12862,   304,   678,   574]])
seq_len: 167


100%|██████████| 166/166 [00:08<00:00, 19.22it/s]


tensor([[    1, 29871, 12074, 26645,  6641,  1328,   297,   278, 10640,   310]])
seq_len: 231


100%|██████████| 230/230 [00:11<00:00, 19.24it/s]


tensor([[    1, 29871,   910,  8589,  7572,  2745,  3839, 29871, 29945,   869]])
seq_len: 122


100%|██████████| 121/121 [00:06<00:00, 19.18it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 29871, 29896,   732, 29899, 29992]])
seq_len: 21


100%|██████████| 20/20 [00:01<00:00, 19.06it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871, 25065,  1919,  2645,  1438,  8820,   297,   967, 18983]])
seq_len: 195


100%|██████████| 194/194 [00:09<00:00, 19.40it/s]


tensor([[    1, 29871,  1551,   278,  7250,   310,  3839, 29871, 29896,  1919]])
seq_len: 156


100%|██████████| 155/155 [00:08<00:00, 19.06it/s]


tensor([[    1, 29871,  1551,  3839, 29871, 29946,  1919, 11389,  4515,  3939]])
seq_len: 261


100%|██████████| 260/260 [00:13<00:00, 19.19it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 12788,   310,   612, 24733,   273]])
seq_len: 15


100%|██████████| 14/14 [00:00<00:00, 19.29it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  1551,   278,  7250,   310,  3839, 29871, 29896,   278]])
seq_len: 98


100%|██████████| 97/97 [00:05<00:00, 19.28it/s]


tensor([[    1, 29871,  1551,   278,  7250,   310,  3839, 29871, 29896,  1919]])
seq_len: 130


100%|██████████| 129/129 [00:06<00:00, 19.50it/s]


tensor([[    1, 29871,   319,  6938,  1919, 29871, 29906,   299, 10863,   261]])
seq_len: 309


100%|██████████| 308/308 [00:16<00:00, 19.10it/s]


tensor([[    1, 29871,  4644, 11354,   550,   750,   884, 26733,   612, 24733]])
seq_len: 167


100%|██████████| 166/166 [00:08<00:00, 19.19it/s]


tensor([[    1, 29871,  2180, 29871, 29900, 29929,   584, 29871, 29941, 29945]])
seq_len: 345


100%|██████████| 344/344 [00:17<00:00, 19.25it/s]


tensor([[    1, 29871,   319, 10608,   471,  7450,   393,   278,  1766,  1475]])
seq_len: 264


100%|██████████| 263/263 [00:13<00:00, 19.27it/s]


tensor([[    1, 29871,   450,  3082,  6795,  2696,  6270,   310,  3839, 29871]])
seq_len: 141


100%|██████████| 140/140 [00:07<00:00, 19.61it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353, 28998, 29871, 29906,   299,  7946]])
seq_len: 16


100%|██████████| 15/15 [00:00<00:00, 20.01it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450, 28998, 29871, 29906,   299,  7946,  1754,   263]])
seq_len: 217


100%|██████████| 216/216 [00:11<00:00, 19.51it/s]


tensor([[    1, 29871,   450,  5337,   260,  7202,   287,  1283,   411,   278]])
seq_len: 166


100%|██████████| 165/165 [00:08<00:00, 19.43it/s]


tensor([[    1, 29871,   910,  9416,  4646,   322,  2462, 10555,  3438,   278]])
seq_len: 175


100%|██████████| 174/174 [00:08<00:00, 19.58it/s]


tensor([[    1, 29871,  4644, 22467,   322,  3148, 13230,  9488, 22822,   297]])
seq_len: 51


100%|██████████| 50/50 [00:02<00:00, 18.45it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  4644, 22467, 28679,   284,   353]])
seq_len: 14


100%|██████████| 13/13 [00:00<00:00, 18.60it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,  8291,  6795,  1131,   547,   472,   512,   305]])
seq_len: 176


100%|██████████| 175/175 [00:09<00:00, 19.43it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  2860,   755,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 19.90it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,  4644, 22467, 29871, 29906,   299,   322, 29871]])
seq_len: 144


100%|██████████| 143/143 [00:07<00:00, 18.78it/s]


tensor([[    1, 29871,  2648,   445,   931,  1919,   278,  3148, 29871, 29906]])
seq_len: 183


100%|██████████| 182/182 [00:09<00:00, 19.03it/s]


tensor([[    1, 29871,  4587,   599,   278,  4644, 22467, 16661,  3412,   278]])
seq_len: 187


100%|██████████| 186/186 [00:09<00:00, 19.79it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353, 28561,   349, 29923,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 18.59it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871, 28561,   349, 29923,  1919,   884,  2998,   408,   313]])
seq_len: 84


100%|██████████| 83/83 [00:04<00:00, 19.47it/s]


9.106623649597168
trial: 450
tensor([[    1, 29871,  2860,   337,   280,  5832,  2211, 20618,   373,   435]])
seq_len: 113


100%|██████████| 112/112 [00:05<00:00, 20.38it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  5298,   353,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 20.83it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  3812,   362,   322,  4655,   732]])
seq_len: 32


100%|██████████| 31/31 [00:01<00:00, 20.09it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,  3719,   471,  8429,   491, 20982,   391,   435]])
seq_len: 175


100%|██████████| 174/174 [00:08<00:00, 20.30it/s]


tensor([[    1, 29871, 28561,   349, 29923,  8794,   411,   435,   573,  7983]])
seq_len: 210


100%|██████████| 209/209 [00:10<00:00, 20.35it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  4358,   446,   322,  6054,   449]])
seq_len: 28


100%|██████████| 27/27 [00:01<00:00, 20.22it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,  1551,  5306, 29871, 29953,  1919, 29871, 29906, 29900]])
seq_len: 224


100%|██████████| 223/223 [00:10<00:00, 20.42it/s]


tensor([[    1, 29871,  1551,  5533, 29871, 29906, 29955,  1919, 29871, 29906]])
seq_len: 138


100%|██████████| 137/137 [00:06<00:00, 20.48it/s]


tensor([[    1, 29871, 28561,   349, 29923,  5492,  1009,  4654,  8693,  3769]])
seq_len: 211


100%|██████████| 210/210 [00:10<00:00, 19.41it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  9333,   297, 19597,   313, 29871]])
seq_len: 20


100%|██████████| 19/19 [00:00<00:00, 19.21it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871, 28561,   349, 29923,  2175,   435,   573,  7983,  1919]])
seq_len: 153


100%|██████████| 152/152 [00:07<00:00, 19.15it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  3323, 25006,  1939,   675,  7983]])
seq_len: 33


100%|██████████| 32/32 [00:01<00:00, 19.40it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   512, 29871, 29906, 29900, 29900, 29953,  1919, 28561]])
seq_len: 260


100%|██████████| 259/259 [00:13<00:00, 19.27it/s]


tensor([[    1, 29871,  1551,  5306, 29871, 29906, 29953,  1919, 29871, 29906]])
seq_len: 414


100%|██████████| 413/413 [00:21<00:00, 19.43it/s]


tensor([[    1, 29871,  1551,  2610, 29871, 29896, 29941,  1919, 29871, 29906]])
seq_len: 91


100%|██████████| 90/90 [00:04<00:00, 19.59it/s]


tensor([[    1, 29871,   512, 29871, 29906, 29900, 29896, 29945,  1919,   372]])
seq_len: 84


100%|██████████| 83/83 [00:04<00:00, 18.92it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353, 22135,   353,   353, 29871,    13]])
seq_len: 9


100%|██████████| 8/8 [00:00<00:00, 18.87it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  6125,   322, 26627,  1199,   353]])
seq_len: 14


100%|██████████| 13/13 [00:00<00:00, 18.20it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871, 28561,   349, 29923, 23233,   263,  3114,   310,  4696]])
seq_len: 185


100%|██████████| 184/184 [00:09<00:00, 19.56it/s]


tensor([[    1, 29871,   402,   290,   267,  1919,   297,  6124,   304,   278]])
seq_len: 90


100%|██████████| 89/89 [00:04<00:00, 18.55it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,   512, 25044,  2063,   353,   353]])
seq_len: 13


100%|██████████| 12/12 [00:00<00:00, 18.99it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   450,  3719,   525, 29879,  7112,  2063,  3160,   379]])
seq_len: 173


100%|██████████| 172/172 [00:08<00:00, 19.25it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,  5158,  5144,   353,   353, 29871,    13]])
seq_len: 10


100%|██████████| 9/9 [00:00<00:00, 18.63it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   435,  1965,   313, 16038,  1816,  5346,   402,   290]])
seq_len: 26


100%|██████████| 25/25 [00:01<00:00, 18.66it/s]


tensor([[    1, 29871, 11019,  3201, 10859,   313,  5677,   331, 21071,  3767]])
seq_len: 26


100%|██████████| 25/25 [00:01<00:00, 19.24it/s]


tensor([[    1, 29871, 12051, 29920,  2911,   313, 12051, 26954,  1723,   813]])
seq_len: 22


100%|██████████| 21/21 [00:01<00:00, 18.71it/s]


tensor([[    1, 29871, 27912, 17328,   313, 22478,  3164,   804,   575,  4034]])
seq_len: 24


100%|██████████| 23/23 [00:01<00:00, 19.61it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871,   353,   353,   353,  3812,   261,  5144,   353,   353]])
seq_len: 13


100%|██████████| 12/12 [00:00<00:00, 19.10it/s]


tensor([[1]])
seq_len: 1


0it [00:00, ?it/s]


tensor([[    1, 29871, 10015, 28944, 29879,   313,   450,   383,  5621,  1723]])
seq_len: 27


100%|██████████| 26/26 [00:01<00:00, 19.09it/s]


tensor([[    1, 29871,   678,   328,  4111,  1416,   359,   313,   678,   466]])
seq_len: 29


100%|██████████| 28/28 [00:01<00:00, 18.69it/s]

9.04964828491211


In [ ]:
import warnings

warnings.filterwarnings("ignore")

import torch
import argparse
import json
import os
import time
import re
import sys

from tqdm import tqdm
from streaming_llm.utils import load, download_url, load_jsonl
from streaming_llm.enable_streaming_llm import enable_streaming_llm

### added ####
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.embeddings import HuggingFaceEmbeddings
#############

@torch.no_grad()
def greedy_generate(model, tokenizer, input_ids, past_key_values, max_gen_len, f):
    outputs = model(
        input_ids=input_ids,
        past_key_values=past_key_values,
        use_cache=True,
    )
    past_key_values = outputs.past_key_values
    pred_token_idx = outputs.logits[:, -1, :].argmax(dim=-1).unsqueeze(1)
    generated_ids = [pred_token_idx.item()]
    pos = 0
    for _ in range(max_gen_len - 1):
        outputs = model(
            input_ids=pred_token_idx,
            past_key_values=past_key_values,
            use_cache=True,
        )
        past_key_values = outputs.past_key_values
        pred_token_idx = outputs.logits[:, -1, :].argmax(dim=-1).unsqueeze(1)
        generated_ids.append(pred_token_idx.item())
        generated_text = (
            tokenizer.decode(
                generated_ids,
                skip_special_tokens=True,
                clean_up_tokenization_spaces=True,
                spaces_between_special_tokens=False,
            )
            .strip()
            .split(" ")
        )

        now = len(generated_text) - 1
        if now > pos:
            f.write(" ".join(generated_text[pos:now]) + " ")
            print(" ".join(generated_text[pos:now]), end=" ", flush=True)
            pos = now


        if pred_token_idx == tokenizer.eos_token_id:
            break
    print(" ".join(generated_text[pos:]), flush=True)
    f.write(" ".join(generated_text[pos:]) + " \n")
    return past_key_values


@torch.no_grad()
def streaming_inference(model, tokenizer, prompts, kv_cache=None, max_gen_len=1000):
    past_key_values = None
    f = open("summary_rag_brief.txt", "w")
    #### new ####
    token_st = 0
    token_lens = []
    model_name = "all-MiniLM-L6-v2"
    model_kwargs = {'device': 'cpu'}
    embedding = HuggingFaceEmbeddings(model_name=model_name,
                                    model_kwargs=model_kwargs)
    ###############
    for idx, prompt in enumerate(prompts):
        prompt = "USER: " + prompt + "\n\nASSISTANT: "
        print("\n" + prompt, end="")
        input_ids = tokenizer(prompt, return_tensors="pt").input_ids

        input_ids = input_ids.to(model.device)
        seq_len = input_ids.shape[1]

        #### new ######
        token_lens.append(token_st)
        token_st += seq_len
        keeps = None
        if idx > 5:
            db = Chroma.from_texts(prompts[:idx], embedding)
            retriever = db.as_retriever(search_kwargs={'k': 1})
            retrieved_docs = retriever.invoke(prompt)
            retrieved_idx = prompts.index(retrieved_docs[0].page_content)
            if retrieved_idx != -1:
                keeps  = (
                    seq_len,
                    [(
                        token_lens[retrieved_idx],
                        token_lens[retrieved_idx] + seq_len
                    )]
                )
                print(keeps)

        ###############

        if kv_cache is not None:
            space_needed = seq_len + max_gen_len
            past_key_values = kv_cache.evict_for_space(past_key_values,
                                                       space_needed,
                                                       keeps=None)
            torch.cuda.empty_cache()

        past_key_values = greedy_generate(
            model, tokenizer, input_ids, past_key_values, max_gen_len=max_gen_len, f=f
        )

    f.close()
#### args ####
model_name_or_path = "lmsys/vicuna-7b-v1.5"
enable_streaming = True
start_size = 4
recent_size = 2000
###############

#### prompt #####
with open("long/nfu.txt") as f:
    longprompt = f.read()

# texts = ["\n".join(lines)]#[i:i+7]) for i in range(0, len(lines), 7)]
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1500, chunk_overlap=40)
texts = text_splitter.split_text(longprompt)
print(f'number of chunks: {len(texts)}')
texts = ["Summarize briefly the following text in English. \n" + text for text in texts]
model, tokenizer = load(model_name_or_path)


prompts = texts
if enable_streaming:
    kv_cache = enable_streaming_llm(
        model, start_size=start_size, recent_size=recent_size
    )
else:
    kv_cache = None

streaming_inference(
    model,
    tokenizer,
    prompts,
    kv_cache,
)

number of chunks: 229
Loading model from lmsys/vicuna-7b-v1.5 ...


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

StartRecentKVCache: 4, 2000

USER: Summarize briefly the following text in English. 
The Project Gutenberg eBook of Notes from the Underground
    
This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg License included with this ebook or online
at www.gutenberg.org. If you are not located in the United States,
you will have to check the laws of the country where you are located
before using this eBook.

Title: Notes from the Underground


Author: Fyodor Dostoyevsky

Release date: July 1, 1996 [eBook #600]
                Most recently updated: December 26, 2021

Language: English



*** START OF THE PROJECT GUTENBERG EBOOK NOTES FROM THE UNDERGROUND ***



Notes from the Underground

by Fyodor Dostoyevsky


Contents

 NOTES FROM THE UNDERGROUND

 PART I Underground
 I
 II
 III
 IV
 V
 VI
 VII
 VIII
 IX


KeyboardInterrupt: ignored

In [ ]:
with open("summary_new_new_map_rag.txt") as f:
    total_count = 0
    for line in f.readlines():
        print(len(line.split()))
        total_count += len(line.split())
print(total_count)

94
389
93
299
27
86
68
46
1102


In [ ]:
torch.cuda.empty_cache()

In [ ]:
nlls = []
with open("outputs/debug_w_rag/log.txt") as f:
    for line in f.readlines():
        nlls.append(float(line.split()[0]))
nlls = torch.Tensor(nlls)

In [ ]:
import torch
m_ppl = torch.exp(nlls.mean()).mean()
std_ppl = torch.exp(nlls.std())

In [ ]:
print(m_ppl, std_ppl)

tensor(10.4099) tensor(20.6830)
